create schema if not exists app_stakeholdercomms;

create table if not exists app_stakeholdercomms.comms_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source_label text not null,
  comms_type text not null,
  audience text not null,
  tone text not null,
  subject text not null,
  status text not null,
  completeness_pct integer not null,
  confidence text not null,
  key_messages jsonb not null default '[]'::jsonb,
  actions jsonb not null default '[]'::jsonb,
  draft text not null,
  prompt_hits jsonb not null default '[]'::jsonb,
  warnings jsonb not null default '[]'::jsonb
);

create table if not exists app_stakeholdercomms.comms_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source_label text not null,
  status text not null,
  completeness_pct integer not null,
  confidence text not null,
  warning_count integer not null default 0
);
