create schema if not exists app_lossratiotriangulator;

create table if not exists app_lossratiotriangulator.app_lossratiotriangulator_analysis_runs (
  id bigint generated by default as identity primary key,
  request_id uuid not null unique,
  source_label text,
  triangle_text text not null,
  question text,
  summary jsonb not null,
  triangle jsonb not null,
  ldfs jsonb not null,
  accident_year_results jsonb not null,
  methodology jsonb not null,
  audit_notes jsonb not null,
  prompt_hits jsonb not null,
  whitespace_rows jsonb not null,
  raw_analysis jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists app_lossratiotriangulator.app_lossratiotriangulator_audit (
  id bigint generated by default as identity primary key,
  request_id uuid not null,
  stage text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_lossratiotriangulator_runs_created_at
  on app_lossratiotriangulator.app_lossratiotriangulator_analysis_runs (created_at desc);

create index if not exists idx_lossratiotriangulator_audit_request_id
  on app_lossratiotriangulator.app_lossratiotriangulator_audit (request_id, created_at desc);

grant usage on schema app_lossratiotriangulator to anon, authenticated, service_role;
grant all privileges on all tables in schema app_lossratiotriangulator to anon, authenticated, service_role;
grant all privileges on all sequences in schema app_lossratiotriangulator to anon, authenticated, service_role;
alter default privileges in schema app_lossratiotriangulator grant all on tables to anon, authenticated, service_role;
alter default privileges in schema app_lossratiotriangulator grant all on sequences to anon, authenticated, service_role;
