create schema if not exists app_treatystructure;

create table if not exists app_treatystructure.app_treatystructure_analysis_runs (
  id bigint generated by default as identity primary key,
  request_id uuid not null unique,
  source_label text,
  raw_input text not null,
  question text,
  summary jsonb not null default '{}'::jsonb,
  raw_analysis jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists app_treatystructure.app_treatystructure_audit (
  id bigint generated by default as identity primary key,
  request_id uuid not null,
  stage text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_app_treatystructure_analysis_runs_created_at
  on app_treatystructure.app_treatystructure_analysis_runs (created_at desc);

create index if not exists idx_app_treatystructure_audit_created_at
  on app_treatystructure.app_treatystructure_audit (created_at desc);

grant usage on schema app_treatystructure to anon, authenticated, service_role;
grant all privileges on all tables in schema app_treatystructure to anon, authenticated, service_role;
grant all privileges on all sequences in schema app_treatystructure to anon, authenticated, service_role;
alter default privileges in schema app_treatystructure grant all on tables to anon, authenticated, service_role;
alter default privileges in schema app_treatystructure grant all on sequences to anon, authenticated, service_role;
