create schema if not exists app_claimsleakage;

create table if not exists app_claimsleakage.app_claimsleakage_analysis_runs (
  id bigint generated by default as identity primary key,
  request_id uuid not null unique,
  source_label text,
  raw_input text not null,
  question text,
  summary jsonb not null default '{}'::jsonb,
  raw_analysis jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists app_claimsleakage.app_claimsleakage_audit (
  id bigint generated by default as identity primary key,
  request_id uuid not null,
  stage text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_app_claimsleakage_analysis_runs_created_at
  on app_claimsleakage.app_claimsleakage_analysis_runs (created_at desc);

create index if not exists idx_app_claimsleakage_audit_created_at
  on app_claimsleakage.app_claimsleakage_audit (created_at desc);

grant usage on schema app_claimsleakage to anon, authenticated, service_role;
grant all privileges on all tables in schema app_claimsleakage to anon, authenticated, service_role;
grant all privileges on all sequences in schema app_claimsleakage to anon, authenticated, service_role;
alter default privileges in schema app_claimsleakage grant all on tables to anon, authenticated, service_role;
alter default privileges in schema app_claimsleakage grant all on sequences to anon, authenticated, service_role;
