create schema if not exists app_portfolioshowcase;

create table if not exists app_portfolioshowcase.app_portfolioshowcase_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  request_id text not null unique,
  source_label text,
  showcase_text text not null,
  showcase_score integer not null,
  showcase_band text not null,
  status text not null,
  completeness_pct integer not null,
  confidence text not null,
  strengths jsonb not null default '[]'::jsonb,
  blockers jsonb not null default '[]'::jsonb,
  next_actions jsonb not null default '[]'::jsonb,
  prompt_hits jsonb not null default '[]'::jsonb,
  warnings jsonb not null default '[]'::jsonb,
  raw_analysis jsonb not null
);

create table if not exists app_portfolioshowcase.app_portfolioshowcase_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  request_id text not null,
  stage text not null,
  payload jsonb not null default '{}'::jsonb
);

grant usage on schema app_portfolioshowcase to anon, authenticated, service_role;
grant all privileges on all tables in schema app_portfolioshowcase to anon, authenticated, service_role;
grant all privileges on all sequences in schema app_portfolioshowcase to anon, authenticated, service_role;
alter default privileges in schema app_portfolioshowcase grant all on tables to anon, authenticated, service_role;
alter default privileges in schema app_portfolioshowcase grant all on sequences to anon, authenticated, service_role;
